services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ip-whitelist-backend
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./whitelist.txt:/data/whitelist.txt

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ip-whitelist-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  clientservice:
    build:
      context: ./clientservice
      dockerfile: Dockerfile
    container_name: ip-whitelist-clientservice
    depends_on:
      - backend
    volumes:
      - ./whitelist.txt:/data/whitelist.txt

  squid:
    image: ubuntu/squid:4.10-20.04_beta
    container_name: squid
    ports:
      - "3128:3128"
    volumes:
      - ./whitelist.txt:/data/whitelist.txt
      - ./squid.conf:/etc/squid/squid.conf:ro
      - ./passwd:/etc/squid/passwd
    depends_on:
      - clientservice